Fix array initialization for pg_attribute_encoding check
Fix thinko in sizing the attnum_entry_present array in the
check_attribute_encoding_entry_exist() function. It should be
MaxHeapAttributeNumber, instead of the size of the pointer (8 bytes).

Because of this bad initialization, any table having greater or equal to
9 columns, would fail to have their AM altered to ao_column with the
following error message:

CREATE TABLE heap2co2(a int, b int, c int, d int, e int, f int, g int, h int, i int);
ALTER TABLE heap2co2 SET ACCESS METHOD ao_column;
ERROR:  could not find tuple for attnum 9 for relid 24576 during scan on pg_attribute_encoding (pg_attribute_encoding.c:156)