[Orca] Remove unused system cols for ao tables in DXL (#17555)
**Issue:**
For a query like:
```
-- Setup
create table test(i int) with (appendonly=true);
insert into test values(1);
set optimizer_enable_multiple_distinct_aggs=on;  -- enable this guc to expose this issue
-- Issue query
select count(distinct (i%5)) cnt1 ,count(distinct (i%10)) cnt2 from test;
```
Following error is happening:
```
ERROR:  cannot retrieve a system column in this context  (seg1 slice1 127.0.0.1:7003 pid=34091)
```

**Cause:**
For above query, plan looks like:
```
                        QUERY PLAN
----------------------------------------------------------
 Sequence
   ->  Shared Scan (share slice:id 0:0)
         ->  Gather Motion 3:1  (slice1; segments: 3)
               ->  Seq Scan on test
   ->  Nested Loop
         Join Filter: true
         ->  Aggregate
               ->  Shared Scan (share slice:id 0:0)
         ->  Materialize
               ->  Aggregate
                     ->  Shared Scan (share slice:id 0:0)
 Optimizer: GPORCA
(12 rows)
```
If the `Shared Scan` node under `Sequence` node is viewed as an expr in physical plan, it looks like:
```
CPhysicalCTEProducer (0), Columns: ["i" (10), "ctid" (11), "xmin" (12), "cmin" (13), "xmax" (14), "cmax" (15), "tableoid" (16), "gp_segment_id" (17)]   rows:1   width:34  rebinds:1   cost:431.000155   origin: [Grp:72, GrpExpr:1]
```
And the `Shared Scan` node under `Aggregate` looks like:
```
CPhysicalCTEConsumer (0), Columns: ["i" (0), "ctid" (1), "xmin" (2), "cmin" (3), "xmax" (4), "cmax" (5), "tableoid" (6), "gp_segment_id" (7)]   rows:1   width:34  rebinds:1   cost:431.000010   origin: [Grp:17, GrpExpr:1]
```
`CPhysicalCTEProducer` and `CPhysicalCTEConsumer` both are expected to output the columns `cmin`, `xmin`, `cmax`, `xmax`.
Since the system columns `cmin`, `xmin`, `cmax`, `xmax` are not present in `test` table, 
it causes an error during execution.

**RCA:**
System columns `cmin`, `xmin`, `cmax`, `xmax`
 were not being added in AO, AOCO tables in 6X for Orca plan's Dxl.
Code for this can be seen at [CTranslatorRelcacheToDXL::AddSystemColumns](https://github.com/greenplum-db/gpdb/blob/bcbaaead795b417d18644f36f334827f0815cf37/src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp#L1011).

In 7X, they were being added in Orca again since they were part of `pg_attribute` table.
This change is done in [pr#11708](https://github.com/greenplum-db/gpdb/pull/11708). 
Github issue discussing these columns for AO, AOCO tables: https://github.com/greenplum-db/gpdb/issues/11844

Recently, these columns are removed from pg_attribute table.
This is done in [pr#15839](https://github.com/greenplum-db/gpdb/pull/15839).
The PR above is also discussed in same issue mentioned above.

**Changes**
 1. Orca now generates the correct system columns that exist in accordance with the catalog.

2. A mismatch between parent/child system columns for 
   a heap parent with ao child created unnecessary complexity during static partition pruning
   Since partition constraints can't be defined on system columns,
   we now skip mapping system columns from parent to child during translating partition constraints from DXL to .

3. Fix regression case plan changes:
   With decrease in number of columns of appendonly tables,
   cost of `CPhysicalTableScan` expr for an AO table decreased
   because of the decrease in `width` value of the same.
   causing some plan changes.

Addresses issue https://github.com/greenplum-db/gpdb/issues/17166.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community